version: 2

services:
  - type: web
    name: eventy-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
      - key: MONGO_URI
        value: mongodb+srv://dapkerushikesh:123456@eventy.l1rvzct.mongodb.net/eventy
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: your_email@gmail.com
      - key: EMAIL_PASS
        value: your_app_password
